apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://185.150.11.76:8888
  name: logstash
contexts:
- context:
    cluster: logstash
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
