---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-namespaces
  namespace: shell-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitor-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #name: monitor-namespaces
  name: cluster-admin # is just used for the demo, don't do this!
subjects:
  - kind: ServiceAccount
    name: monitor-namespaces
    namespace: shell-operator
