apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-demo_read-only
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: /oebb_k8s_read-only
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: /oebb_k8s_${CLUSTER}_read-only
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: /oebb_k8s_${CLUSTER}_demo_read-only
  apiGroup: rbac.authorization.k8s.io